### ISSUE TITLE
Does not load worlds in 1.16

### ISSUE THREAD

**Issue by Monocucuy** [embeddedt/ModernFix#106]
The following error shows a bug in loading the world:
Suspicious async chunkload, pass -Dmodernfix.debugBadChunkloading=true for more details
[19:24:27] [Worker-Main-13/ERROR]: Async chunk load took way too long, this needs to be reported to the appropriate mod.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1763) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1907) ~[?:1.8.0_51]
	at net.minecraft.world.server.ServerChunkProvider.handler$zef000$bailIfServerDead(ServerChunkProvider.java:2599) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java) [?:?]
	at net.minecraft.world.World.func_217353_a(World.java:167) [?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:112) [?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:163) [?:?]
	at net.minecraft.world.World.func_180495_p(World.java:379) [?:?]
	at com.corosus.zombieawareness.ZAUtil.canSpawnTrace(ZAUtil.java:620) [?:1.16.5-1.12]
	at com.corosus.zombieawareness.ZAUtil.hookSoundEvent(ZAUtil.java:469) [?:1.16.5-1.12]
	at net.minecraft.world.server.ServerWorld.redirect$zhd000$broadcast(ServerWorld.java:2546) [?:?]
	at net.minecraft.world.server.ServerWorld.func_184148_a(ServerWorld.java:995) [?:?]
	at net.minecraft.entity.Entity.func_184185_a(Entity.java:885) [?:?]
	at net.minecraft.entity.item.ItemFrameEntity.func_174864_a(SourceFile:277) [?:?]
	at com.bobmowzie.mowziesmobs.server.world.feature.structure.BarakoaVillagePieces$HousePiece.func_186175_a(BarakoaVillagePieces.java:336) [?:1.5.27]
	at net.minecraft.world.gen.feature.structure.TemplateStructurePiece.func_230383_a_(SourceFile:77) [?:?]
	at com.bobmowzie.mowziesmobs.server.world.feature.structure.BarakoaVillagePieces$Piece.func_230383_a_(BarakoaVillagePieces.java:227) [?:1.5.27]
	at net.minecraft.world.gen.feature.structure.StructureStart.func_230366_a_(StructureStart.java:65) [?:?]
	at net.minecraft.world.biome.Biome.lambda$generate$20(Biome.java:234) [?:?]
	at net.minecraft.world.biome.Biome$$Lambda$24673/759907177.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at it.unimi.dsi.fastutil.longs.LongIterator$$Lambda$24667/241389650.accept(Unknown Source) [fastutil-8.2.1.jar:?]
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189) [?:1.8.0_51]
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53) [fastutil-8.2.1.jar:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_51]
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:233) [?:?]
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) [?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) [?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1977/1998173727.doWork(Unknown Source) [?:?]
	at net.minecraft.world.chunk.ChunkStatus.mdd34bd8$lambda$injectLightmapSetup$1$4(ChunkStatus.java:546) [?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1978/998007202.doWork(Unknown Source) [?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) [?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) [?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$24625/1161761681.apply(Unknown Source) [?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) [datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) [?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$24609/1055102561.apply(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) [?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$24623/1422177852.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[19:24:31] [qtp596444568-198/WARN]: File at resource location not found: undefined
[19:25:02] [WebSocketConnectReadThread-84/INFO]: Closed connection to Essential Connection Manager (code=4500, reason=SERVER_KEEP_ALIVE_TIMEOUT (68246ms), remote=false), connection was open for 101996ms

**Comment by embeddedt** [comment]
This is a bug in Zombie Awareness, please add https://www.curseforge.com/minecraft/mc-mods/zombie-awareness-freeze-fix.

**Comment by embeddedt** [comment]
Closing as I am pretty sure adding the above mod will solve this problem and the thread dump points directly to Zombie Awareness as the culprit.
