### ISSUE TITLE
Crash on new world creation

### ISSUE THREAD

**Issue by NielsPilgaard** [embeddedt/ModernFix#128]
I tried adding ModernFix to Enigmatica 6, but it hung on initial world load. There was no crash report, but this was in the latest.log:

Latest log snippet: https://gist.github.com/NielsPilgaard/8ce71ceafa795969e00f7d3b1a05a794

Full latest log: https://gist.github.com/NielsPilgaard/747c1875aab7f69a2aaf03ef8d810598

```
[13Jun2023 18:59:47.538] [Server thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: 0
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2531/1585558534@19e192e4
java.lang.ArrayIndexOutOfBoundsException: 0
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.put(Object2ObjectArrayMap.java:292)
	at org.embeddedt.modernfix.util.CanonizingStringMap.put(CanonizingStringMap.java:63)
	at org.embeddedt.modernfix.util.CanonizingStringMap.put(CanonizingStringMap.java:16)
	at net.minecraft.nbt.CompoundNBT.func_74757_a(CompoundNBT.java:174)
	at wile.engineersdecor.ModConfig.apply(ModConfig.java:757)
	at wile.engineersdecor.ModEngineersDecor$ForgeEvents.onConfigLoad(ModEngineersDecor.java:97)
	at wile.engineersdecor.ModEngineersDecor$$Lambda$20989/395860675.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/1585558534.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2792/1073849761.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2683/1904318683.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:138)
	at net.minecraftforge.fml.ModContainer$$Lambda$28397/1072985353.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:138)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:76)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:92)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:69)
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$28378/1422774106.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:69)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:80)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:59)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$41165/2101407080.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[13Jun2023 18:59:47.541] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.put(Object2ObjectArrayMap.java:292) ~[fastutil-8.2.1.jar:?]
	at org.embeddedt.modernfix.util.CanonizingStringMap.put(CanonizingStringMap.java:63) ~[?:5.0.1+mc1.16.5]
	at org.embeddedt.modernfix.util.CanonizingStringMap.put(CanonizingStringMap.java:16) ~[?:5.0.1+mc1.16.5]
	at net.minecraft.nbt.CompoundNBT.func_74757_a(CompoundNBT.java:174) ~[?:?]
	at wile.engineersdecor.ModConfig.apply(ModConfig.java:757) ~[?:1.1.19]
	at wile.engineersdecor.ModEngineersDecor$ForgeEvents.onConfigLoad(ModEngineersDecor.java:97) ~[?:1.1.19]
	at wile.engineersdecor.ModEngineersDecor$$Lambda$20989/395860675.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/1585558534.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2792/1073849761.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2683/1904318683.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:138) ~[?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$28397/1072985353.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:138) ~[?:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:76) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:92) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:69) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$28378/1422774106.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:69) ~[?:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:80) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:59) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$41165/2101407080.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[13Jun2023 18:59:47.572] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID b7cbe974-6ab8-4656-8b25-9c49d4433366
[13Jun2023 18:59:47.584] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\Users\Niels\Curseforge\Minecraft\Instances\Enigmatica6\crash-reports\crash-2023-06-13_18.59.47-server.txt
[13Jun2023 18:59:47.587] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[13Jun2023 18:59:47.587] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[13Jun2023 18:59:47.587] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[13Jun2023 18:59:47.587] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.NullPointerException: null
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:538) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:167) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$41165/2101407080.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by embeddedt** [comment]
This is a known issue with Engineer's Decor, it appears to store its config
as an NBT object and then access it from multiple threads, which
occasionally causes crashes. (Pretty sure this can occur without ModernFix
as well.)

If you try to create a world again it will likely work fine.

**Comment by NielsPilgaard** [comment]
Ah I see, odd that it hasn't happened to me before adding ModernFix though.

Second load, new crash: https://gist.github.com/NielsPilgaard/9625da9404a36eb16ab435c8b830e377

Looks unrelated to ModernFix, but the pack was pretty stable before adding it :/
I think I'll just give up on adding it to E6 😅

**Comment by embeddedt** [comment]
This one might be related to the `mixin.perf.async_jei` option; there may be a JEI plugin in E6 that doesn't work well with this optimization.
