### ISSUE TITLE
Error loading at start of execution Minecraft 1.18.2

### ISSUE THREAD

**Issue by Billetiado10** [embeddedt/ModernFix#184]
Version: 
modernfix-forge-5.3.2+mc1.18.2.jar
Minecraft Forge 1.18.2 Version 40.2.10

Crash Report

00:48:15.037
game
... 37 more
00:48:15.037
game
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/item/ItemStack::getItemDirect with priority 1000 cannot inject into net/minecraft/world/item/ItemStack::m_41619_()Z merged by com.abdelaziz.canary.mixin.item.ItemStackMixin with priority 1000 [PREINJECT Applicator Phase -> modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin -> Prepare Injections ->  -> redirect$zem000$getItemDirect(Lnet/minecraft/world/item/ItemStack;)Lnet/minecraft/world/item/Item; -> Prepare]
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
00:48:15.037
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
00:48:15.037
game
... 37 more

images of the crash

stays as a background program running
![Captura de pantalla 2023-07-25 005027](https://github.com/embeddedt/ModernFix/assets/76263374/50e3f330-3ebb-4313-9435-994b6e900b12)

**Comment by embeddedt** [comment]
Please take a look at the top of your `latest.log` file, you likely have a missing dependency for another mod, which causes Forge to cause ModernFix to crash.
