### ISSUE TITLE
Error in console when stopping server

### ISSUE THREAD

**Issue by ICHTLAY** [embeddedt/ModernFix#213]
Have this exception when I trying to stop server. Seems like everything works fine, but I interested in this exception specifically because I don't have it in log files, only in console.

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "config" is null
        at TRANSFORMER/modernfix@5.3.2+mc1.19.2/org.embeddedt.modernfix.forge.config.NightConfigFixer.toWriteSyncConfig(NightConfigFixer.java:89)
        at TRANSFORMER/modernfix@5.3.2+mc1.19.2/org.embeddedt.modernfix.forge.config.ConfigFixer$LockingConfigHandler.accept(ConfigFixer.java:46)
        at TRANSFORMER/modernfix@5.3.2+mc1.19.2/org.embeddedt.modernfix.forge.config.ConfigFixer$LockingConfigHandler.accept(ConfigFixer.java:35)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.6/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.6/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150)
        at TRANSFORMER/puzzleslib@4.4.3/fuzs.puzzleslib.config.core.ForgeConfigFileTypeHandler$ConfigWatcher.run(ForgeConfigFileTypeHandler.java:143)
        at TRANSFORMER/modernfix@5.3.2+mc1.19.2/org.embeddedt.modernfix.forge.config.NightConfigFixer$MonitoringConfigTracker.protectFromSaving(NightConfigFixer.java:127)
        at TRANSFORMER/modernfix@5.3.2+mc1.19.2/org.embeddedt.modernfix.forge.config.NightConfigFixer$MonitoringConfigTracker.run(NightConfigFixer.java:148)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
```

**Comment by embeddedt** [comment]
This issue is fixed in newer versions of ModernFix as far as I know.

**Comment by ICHTLAY** [comment]
> This issue is fixed in newer versions of ModernFix as far as I know.

Yeah, I updated mod on client but forgot on server, just tried and I no longer have this exception, why I am so dumb... Thanks :)
