### ISSUE TITLE
Getting Error when using ModernFix together with Weapon Leveling

### ISSUE THREAD

**Issue by s3tupw1zard** [embeddedt/ModernFix#226]
I want to report a bug. 

I'm getting the following error:

```
2023-08-21 20:07:45,263 main WARN Advanced terminal features are not available in this environment
20:07:45.451
game
[20:07:45] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, s3tupw1zard, --version, forge-40.2.10, --gameDir, C:\Users\s3tupw1zard\curseforge\minecraft\Instances\s3tupw1zard's Pack, --assetsDir, C:\Users\s3tupw1zard\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, a7882287ad6a4d4eb24607dbc4351b36, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ODA5ZDE1MmUtZWVmOS00MzcyLWI1N2QtNmVlYjJmNWZlYjg5, --xuid, 2535464763752313, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.10, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
20:07:45.455
game
[20:07:45] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
20:07:45.648
game
[20:07:45] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/s3tupw1zard/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
20:07:46.567
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.10\fmlcore-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.571
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.10\javafmllanguage-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.574
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.10\lowcodelanguage-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.577
game
[20:07:46] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\s3tupw1zard\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.10\mclanguage-1.18.2-40.2.10.jar is missing mods.toml file
20:07:46.915
game
[20:07:46] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 8 dependencies adding them to mods collection
20:07:47.925
game
Init ItemPhysic coremods ...
20:07:49.978
game
Exception in thread "main" java.lang.module.ResolutionException: Modules weaponleveling and MixinExtras.beta._9 export package com.llamalad7.mixinextras to module betterfortresses
20:07:49.979
game
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
20:07:49.979
game
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
20:07:49.979
game
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
20:07:49.979
game
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
20:07:49.979
game
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
20:07:49.979
game
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
20:07:49.979
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
20:07:49.979
game
at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

When I remove ModernFix or Weapon Leveling everything works perfectly and the game starts.

**Comment by embeddedt** [comment]
At first glance it looks like Weapon Leveling is using MixinExtras (a library) incorrectly, which will cause a crash with mods that include it the official way like mine. However I am consulting with more knowledgeable people to be sure.

As a temporary workaround you can downgrade to ModernFix 5.6.1 which is the last version to not use MixinExtras.

If you are tech-savvy another workaround I found is manually opening the Weapon Leveling JAR and deleting the file inside `META-INF/services`.

**Comment by embeddedt** [comment]
I've received confirmation that this can't be fixed without an update on the other mod's end.
