### ISSUE TITLE
[1.18.2][Forge] Crash on startup for 5.7.x when installed alongside Debugify 1.11.0

### ISSUE THREAD

**Issue by ullebe1** [embeddedt/ModernFix#233]
I'm experiencing a crash on launch after updating from ModernFix 5.6.1 to 5.7.0, 5.7.1 or 5.7.2, using Forge 40.2.0, 40.2.4 and 40.2.10
The crash seems to be an incompatibility with Debugify 1.11.0.

The important part of the log seems to be:
```
Caused by: java.lang.module.ResolutionException: Modules debugify and MixinExtras.beta._9 export package com.llamalad7.mixinextras to module farsight_view
```

Possibly distantly related to #132, however modloaders and Minecraft versions are different. 

If there is anything I can do to help solve this issue, please let me know.

<details>
  <summary>Log</summary>

```
Mods:
  [✔] AI-Improvements-1.18.2-0.5.2
  [✔] appleskin-forge-mc1.18.2-2.4.1
  [✔] architectury-4.11.93-forge
  [✔] badpackets-forge-0.1.3
  [✔] balm-3.2.6
  [✔] better-loading-screen-1.4.0
  [✔] betterbiomeblend-1.18.2-1.3.5-forge
  [✔] BetterF3-3.0.0-Forge-1.18.2
  [✔] BetterPingDisplay-1.18.2-1.1
  [✔] canary-mc1.18.2-0.2.4
  [✔] cloth-config-6.5.102-forge
  [✔] controllable-0.17.0-1.18.2
  [✔] create-1.18.2-0.5.1.c
  [✔] debugify-1.11.0-forge-1.18.2
  [✔] dynamiclightsreforged-1.18.2_v1.3.3
  [✔] entityculling-forge-1.6.1-mc1.18.2
  [✔] farsight-1.18.2-1.9
  [✔] ferritecore-4.2.2-forge
  [✔] GameMenuModOption-1.18-Forge-1.14.2
  [✔] jei-1.18.2-forge-10.2.1.1002
  [✔] lazydfu-1.0-1.18+
  [✔] light-overlay-6.0.5-forge
  [✔] lightspeed-1.18.2-1.0.5
  [✔] modernfix-forge-5.7.2+mc1.18.2
  [✔] netherportalfix-forge-1.18.2-9.0.1
  [✔] NoChatLagForge-1.1.0-1.17-1.18
  [✔] oculus-flywheel-compat-1.18.2-0.2.1
  [✔] oculus-mc1.18.2-1.6.4
  [✔] pluto-mc1.18.2-0.0.6
  [✔] preciseblockplacing-1.1.0+1.18.2-forge
  [✔] rubidium_extras-1.18.2_v1.3.2
  [✔] rubidium-0.5.6
  [✔] saturn-mc1.18.2-0.0.4
  [✔] starlight-1.0.2+forge.546ae87
  [✔] wthit-forge-4.13.6
  [✔] Xaeros_Minimap_FP23.6.3_Forge_1.18.2
  [✔] XaerosWorldMap_1.34.0_Forge_1.18.2

Params:
  --username  --version 1.18.2 --gameDir /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/TK-Gaming-local-dev/.minecraft --assetsDir /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 40.2.10 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914

Window size: max (if available)

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 1901


Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-09-02 13:38:54,047 main WARN Advanced terminal features are not available in this environment
[13:38:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <redacted>, --version, 1.18.2, --gameDir, /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/TK-Gaming-local-dev/.minecraft, --assetsDir, /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets, --assetIndex, 1.18, --uuid, <PROFILE ID>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.10, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[13:38:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.7 by Flathub
[13:38:54] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2355!/ Service=ModLauncher Env=CLIENT
[13:38:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/fmlcore/1.18.2-40.2.10/fmlcore-1.18.2-40.2.10.jar is missing mods.toml file
[13:38:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/javafmllanguage/1.18.2-40.2.10/javafmllanguage-1.18.2-40.2.10.jar is missing mods.toml file
[13:38:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/lowcodelanguage/1.18.2-40.2.10/lowcodelanguage-1.18.2-40.2.10.jar is missing mods.toml file
[13:38:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /var/home/<redacted>/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/mclanguage/1.18.2-40.2.10/mclanguage-1.18.2-40.2.10.jar is missing mods.toml file
[13:38:55] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.module.ResolutionException: Modules debugify and MixinExtras.beta._9 export package com.llamalad7.mixinextras to module farsight_view
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	... 8 more
Exiting with ERROR
Process exited with code 2.
```

<details>

**Comment by embeddedt** [comment]
This is Debugify's fault; there is nothing I can do about it. They are not following the proper steps to include MixinExtras in their mod; any mod that doesn't do that will crash with mods that do it properly like mine.

It's most likely they just need to add `mergeServiceFiles()` to their `shadowJar` block in the Gradle file, but this requires updating their mod, which I don't know if they will do on 1.18. :confused:

**Comment by ullebe1** [comment]
Thank you for the detailed response!

I'll open an issue on their repo and refer them to what you wrote. 

EDIT: They don't seem to accept issues for the Forge version anymore.
EDIT2: You were spot on with the required fix, built my own version containing it and now everything works.

**Comment by theshadowake** [comment]
@ullebe1 any chance of uploading a fork to CurseForge or similar so others can use?

**Comment by ullebe1** [comment]
> @ullebe1 any chance of uploading a fork to CurseForge or similar so others can use?

Yes, I'll look into that.

**Comment by theshadowake** [comment]
> 

That would be great, any chance I could get a copy of the .jar in the mean time?

**Comment by ullebe1** [comment]
Better late than never: I'v made a version of the Debugify 1.10.0 available that contains the above mentioned fix: https://github.com/ullebe1/Debugify/releases/tag/1.11.0-fixed

Tagging you @theshadowake, in case you're still interested.
