### ISSUE TITLE
[Crash] java.lang.StackOverflowError: Rendering item | Mod Conflict

### ISSUE THREAD

**Issue by A5ho9999** [embeddedt/ModernFix#238]
Mod Version: https://modrinth.com/mod/modernfix/version/zny6etkd
Fabric: 1.20.1
Loader: 0.14.22

I think it's conflicting with https://modrinth.com/mod/enchanted-vertical-slabs (v1.9)

Log Message
```
java.lang.StackOverflowError: Rendering item
	at net.minecraft.class_4970$class_4971.redirect$gpn000$modernfix$genCacheBeforeGettingFluid(class_4970.java:6403)
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:1214)
	at games.enchanted.registry.types.CombinableVerticalSlabBlock.method_9545(CombinableVerticalSlabBlock.java:192)
	at net.minecraft.class_4970$class_4971.redirect$gpn000$modernfix$genCacheBeforeGettingFluid(class_4970.java:6403)
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:1214)
	at games.enchanted.registry.types.CombinableVerticalSlabBlock.method_9545(CombinableVerticalSlabBlock.java:192)
	at net.minecraft.class_4970$class_4971.redirect$gpn000$modernfix$genCacheBeforeGettingFluid(class_4970.java:6403)
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:1214)
	at games.enchanted.registry.types.CombinableVerticalSlabBlock.method_9545(CombinableVerticalSlabBlock.java:192)
	at net.minecraft.class_4970$class_4971.redirect$gpn000$modernfix$genCacheBeforeGettingFluid(class_4970.java:6403)
	at net.minecraft.class_4970$class_4971.method_26227(class_4970.java:1214)
```

**Comment by embeddedt** [comment]
Fixed in 5.7.4.
