### ISSUE TITLE
Client crash when opening chat window or playing for extended period of time. 

### ISSUE THREAD

**Issue by 31j** [embeddedt/ModernFix#287]
## Version: 
* Minecraft 1.20.2
* Fabric Loader 0.14.24 
* Adoptium JDK 17.0.8 
* Prism Launcher 7.1
* Modern Fix 5.9.1

## Description
Crash occurs after playing for a short while and opening the chat window, if playing for an extended period of time block placing becomes laggy before crashing without opening the chat window. Every crash has the same thing:

```
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.client.util.math.MatrixStack.translate(MatrixStack.java:24)
	at net.minecraft.client.gui.hud.InGameHud.handler$eam000$raised$endChatTranslate(InGameHud.java:1586)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:386)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:927)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1275)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

## Full Crash Report
https://mclo.gs/Je8Fmyr

## Client Log Files
https://mclo.gs/OvtRIYV
https://mclo.gs/nQla3MQ

Edit: Additional note, it does only happen if playing for a tiny bit, if you immediately open the chat window to enter a command or whatnot it will not trigger, it needs a minute or two of game time before it can be triggered.

**Comment by 31j** [comment]
issue is likely a mod-conflict, unable to reproduce with a minimal set of mods (performance & their dependencies + iris) 

<details>
<summary>Mod List</summary>
<br>

* Bobby
* Borderless Mining
* Cloth Config v12
* Debugify
* Dynamic FPS
* EntityCulling-Fabric
* Exordium
* Fabric API
* FastBack
* FastQuit
* FerriteCore
* ImmediatelyFast
* Indium
* Iris
* Krypton
* Lithium
* ModernFix
* More Culling
* Sodium
  - Reese's Sodium Options
  - Sodium Extra
</details>

**Comment by embeddedt** [comment]
ModernFix doesn’t really modify the chat screen or matrix stacks so I
suspect the issue is with another mod.

**Comment by 31j** [comment]
My apologies, I forgot I had updated 3 mods prior to installing this one for the first time today, and erroneously attributed the crash to the addition of this mod. Thank you for pointing me in the right direction and sorry for wasting your time. 

Regards - 31j

Edit: If you are curious it seems that it is the most recent update of controlify causing my issue, the minimum viable reproducible list of mods being Controlify, and its dependencies Fabric API and YACL
