### ISSUE TITLE
Add modid to mixin method names

### ISSUE THREAD

**Issue by ChiefArug** [embeddedt/ModernFix#316]
Can you please add your modid to the names of all methods you add via mixin so that it is easy to tell the source of a mixin from a stacktrace, instead of needing to search the entirety of github or all mod jars in the mods folder for the source of a mixin.

Something like this:
```java

    @Inject(method = "getChunk", at = @At("HEAD"), cancellable = true)
    private void modernfix$bailIfServerDead(int chunkX, int chunkZ, ChunkStatus requiredStatus, boolean load, CallbackInfoReturnable<ChunkAccess> cir) {
        /* ... */
    }
```

Example stacktrace where this would be useful:
```
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.handler$zec000$bailIfServerDead(ServerChunkCache.java:1596)
        ~ cut to shorten ~
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.biome.BiomeManager.m_204214_(BiomeManager.java:79)
    at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.temperature.modifier.BiomeTempModifier.calculate(BiomeTempModifier.java:52)
    at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.temperature.modifier.TempModifier.update(TempModifier.java:60)
    at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.util.Temperature.apply(Temperature.java:114)
    at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.util.Temperature.apply(Temperature.java:130)
    at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.util.Temperature.getTemperatureAt(Temperature.java:138)
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.item.ItemEntity.mdb608ee$lambda$tickFood$0$0(ItemEntity.java:1034)
    at TRANSFORMER/forge@43.2.21/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.item.ItemEntity.handler$bfl000$tickFood(ItemEntity.java:1033)
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:98)
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.track(ServerLevel.java:6240)
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.redirect$dko000$onTickNonPassenger(ServerLevel.java:6256)
        ~ cut to shorten ~
    at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
    at java.base/java.lang.Thread.run(Thread.java:833)
```
There are three mixins in here, all from different mods (your one is near the top). Because they don't have modids in them its impossible to tell which mods they are from without a decompiler or hoping the mod is on github and its not too generic a method name.

**Comment by embeddedt** [comment]
I'm not planning to do this; it just makes the codebase harder to read because every method is now (redundantly) prefixed with `modernfix$` when it's already clear to the developer that they have the ModernFix project open.

Ideally, this should be done by the Mixin library itself at runtime, like Fabric already does. That approach brings all the support benefits with none of the dev-time downsides.

**Comment by ChiefArug** [comment]
This is still a problem.
Yes, it makes dev time ever so slightly more painful. But it makes identifying mixins in stacktraces much easier, and more people get crashes with modernfix mixins in the stacktrace than actually develop modernfix, so I believe the benifeit greatly outweighs the loss.
