### ISSUE TITLE
[1.20.1 Fabric] ModernFix v5.10.1 conflicts with MoreCulling

### ISSUE THREAD

**Issue by dima-dencep** [embeddedt/ModernFix#328]
```console
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "this.field_5408" is null
	at net.minecraft.class_1092.method_4742(class_1092.java:71)
	at net.minecraft.class_773.method_3335(class_773.java:1040)
	at net.minecraft.class_776.method_3349(class_776.java:90)
	at net.minecraft.class_4970$class_4971$class_3752.redirect$eac000$moreculling$shouldDoShapeCache(class_4970.java:2388)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1283)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843)
	at net.minecraft.class_4970$class_4971.mfix$generateCache(class_4970.java:4370)
	at net.minecraft.class_4970$class_4971.redirect$dop000$modernfix$dynamicCacheGen(class_4970.java:4389)
	at net.minecraft.class_4970$class_4971.method_26216(class_4970.java:1009)
	at me.pepperbell.continuity.client.resource.CustomBlockLayers.getLayer(CustomBlockLayers.java:45)
	at net.minecraft.class_4696.handler$zkd000$continuity$onHeadGetBlockLayer(class_4696.java:519)
	at net.minecraft.class_4696.method_23679(class_4696.java)
```

###### This does not happen in v5.10.0

**Comment by embeddedt** [comment]
More Culling needs to fix it on their end; their code seems to assume models are ready too early. https://github.com/FxMorin/MoreCulling/issues/195
