### ISSUE TITLE
Update clear_fabric_mapping_tables for FL 0.15+

### ISSUE THREAD

**Issue by SylisMC** [embeddedt/ModernFix#329]
Noticed this issue in my console.
probably due to mixin.perf.clear_fabric_mapping_tables=true in the config. figured id report it

5.10.1+mc1.20.1

```
[06:16:42] [main/ERROR]: Failed to clear mappings
java.lang.NoClassDefFoundError: net/fabricmc/mapping/tree/TinyMappingFactory
	at org.embeddedt.modernfix.fabric.mappings.MappingsClearer.lambda$clear$0(MappingsClearer.java:36) ~[modernfix-fabric-5.10.1+mc1.20.1.jar:?]
	at org.embeddedt.modernfix.util.CommonModUtil.runWithoutCrash(CommonModUtil.java:17) ~[modernfix-fabric-5.10.1+mc1.20.1.jar:?]
	at org.embeddedt.modernfix.fabric.mappings.MappingsClearer.clear(MappingsClearer.java:23) ~[modernfix-fabric-5.10.1+mc1.20.1.jar:?]
	at org.embeddedt.modernfix.ModernFixPreLaunchFabric.onPreLaunch(ModernFixPreLaunchFabric.java:23) ~[modernfix-fabric-5.10.1+mc1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.ClassNotFoundException: net.fabricmc.mapping.tree.TinyMappingFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 8 more
```

**Comment by embeddedt** [comment]
Thanks for the report; it's because this optimization isn't yet updated to support Fabric Loader 0.15+. The error is harmless and be ignored.

**Comment by SylisMC** [comment]
Gotcha, thanks for all your hard work. even without taking advantage of dynamic resources (incompatibility with physics mod snow) this mod helps make the game run so much smoother. a real must have

**Comment by embeddedt** [comment]
The error message is suppressed as of 5.13.0 if Fabric Loader 0.15.0 or newer is used, as the optimization is no longer needed.
