### ISSUE TITLE
Texture 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [embeddedt/ModernFix#338]
Everything that is marked as an error in my debug.log

at org.embeddedt.modernfix.forge.config.ConfigFixer$LockingConfigHandler.accept(ConfigFixer.java:53) ~[modernfix-forge-5.11.1+mc1.19.2.jar%23498!/:5.11.1+mc1.19.2]
	at org.embeddedt.modernfix.forge.config.ConfigFixer$LockingConfigHandler.accept(ConfigFixer.java:38) ~[modernfix-forge-5.11.1+mc1.19.2.jar%23498!/:5.11.1+mc1.19.2]

[28���.2023 22:34:37.814] [Worker-ResourceReload-2/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:items/globes/globe_chu
[28���.2023 22:34:37.841] [Worker-ResourceReload-0/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:items/globes/globe_dausora
[28���.2023 22:34:38.173] [Worker-ResourceReload-3/ERROR] [ModernFix/]: Using missing texture, unable to load born_in_chaos_v1:blocks/
[28���.2023 22:34:38.202] [Worker-ResourceReload-5/ERROR] [ModernFix/]: Using missing texture, unable to load minecraft:block/cherry_log

[28���.2023 22:34:38.976] [Worker-ResourceReload-2/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/windmill
[28���.2023 22:34:38.976] [Worker-ResourceReload-4/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/biomancy/mascot_outline
[28���.2023 22:34:38.976] [Worker-ResourceReload-1/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/biomancy/mascot_accent
[28���.2023 22:34:38.977] [Worker-ResourceReload-1/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/bevels
[28���.2023 22:34:38.978] [Worker-ResourceReload-5/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/ornate
[28���.2023 22:34:38.980] [Worker-ResourceReload-1/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/treated_wood
[28���.2023 22:34:38.980] [Worker-ResourceReload-1/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/hammer
[28���.2023 22:34:38.981] [Worker-ResourceReload-4/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/wolf_l
[28���.2023 22:34:38.981] [Worker-ResourceReload-1/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/wolf_r
[28���.2023 22:34:38.981] [Worker-ResourceReload-1/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/immersiveengineering/wolf
[28���.2023 22:34:38.982] [Worker-ResourceReload-5/ERROR] [ModernFix/]: Using missing texture, unable to load supplementaries:entity/flags/biomancy/mascot_base

**Comment by embeddedt** [comment]
These warnings are harmless and can be ignored unless there is a specific visual issue in-game.

**Comment by Krimatoria** [comment]
That's the speed of the response)))))
