### ISSUE TITLE
Crash with Dynamic Tree

### ISSUE THREAD

**Issue by EdoEquin0x** [embeddedt/ModernFix#354]
The latest version of dynamic tree for 1.20.1 is incompatible with Modern Fix

> java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.packs.resources.IoSupplier.m_247737_()" because "this.f_215496_" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.packs.resources.IoSupplier.m_247737_()" because "this.f_215496_" is null
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.Resource.m_215507_(Resource.java:46)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.Resource.m_215508_(Resource.java:50)

**Comment by embeddedt** [comment]
Fixed in 5.13.0.
