### ISSUE TITLE
[1.20.4] Incompatible with the latest REI (v14.1.708)

### ISSUE THREAD

**Issue by Wudji** [embeddedt/ModernFix#395]
### Bug Description

Incompatible with the latest REI (v14.1.708) : https://modrinth.com/mod/rei/version/14.1.708+fabric

Tested to be compatible with REI v688: https://modrinth.com/mod/rei/version/14.0.688+fabric

ModernFix: https://modrinth.com/mod/modernfix/version/5.16.0+mc1.20.4

Game version:1.20.4(fabric-api-0.97.0+1.20.4)

### Reproduction Steps

N/A

### Log File

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-04-16 14:51:43
Description: Unexpected error

java.lang.NoSuchMethodError: 'void me.shedaniel.rei.impl.client.search.AsyncSearchManager.<init>(java.util.function.Supplier, java.util.function.Supplier, java.util.function.UnaryOperator)'
	at org.embeddedt.modernfix.searchtree.REIBackedSearchTree.createSearchManager(REIBackedSearchTree.java:110)
	at org.embeddedt.modernfix.searchtree.REIBackedSearchTree.<init>(REIBackedSearchTree.java:25)
	at org.embeddedt.modernfix.searchtree.REIBackedSearchTree$1.getSearchTree(REIBackedSearchTree.java:121)
	at net.minecraft.class_310.md5f13b1$modernfix$lambda$replaceSearchTrees$0$5(class_310.java:25775)
	at net.minecraft.class_1124$class_7457.method_43807(class_1124.java:60)
	at net.minecraft.class_1124.method_43804(class_1124.java:42)
	at net.minecraft.class_310.method_43759(class_310.java:2840)
	at org.embeddedt.modernfix.platform.fabric.ModernFixPlatformHooksImpl.lambda$registerCreativeSearchTrees$2(ModernFixPlatformHooksImpl.java:114)
	at net.minecraft.class_1761.method_47314(class_1761.java:128)
	at net.minecraft.class_634.method_52802(class_634.java:1549)
	at net.minecraft.class_634.method_11120(class_634.java:394)
	at net.minecraft.class_2678.method_11567(class_2678.java:57)
	at net.minecraft.class_2678.method_11054(class_2678.java:14)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

**Comment by benio1394** [comment]
Also it happen the same on 1.20.1

**Comment by alien-sunset** [comment]
same, but mine works with up to REI v699

https://mclo.gs/bFdxfnM

**Comment by embeddedt** [comment]
Fixed in 5.16.1
