### ISSUE TITLE
`dynamic_entity_renderers` causes error when enabled

### ISSUE THREAD

**Issue by Mickeon** [embeddedt/ModernFix#406]
### Bug Description

Joining a world causes the console to print an error: `Failed to create entity model for minecraft:player:
java.lang.RuntimeException: Provider not registered`.

Note that:
- This error does _not_ result in a crash or otherwise unstable behavior, but it can be quite misleading.
- I am using the Custom Player Models mod.

### Reproduction Steps

- Boot up the game.
- Join any world.

### Log File

The entire log file contains information that is either (potentially) irrelevant or personal, however here's around the part where this error happens:
```
[21:47:10] [Render thread/INFO] [ModernFix/]: Dynamic entity renderer hook setup
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:allay
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:armor_stand
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:axolotl
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:bat
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:bee
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:blaze
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:camel
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:cat
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:cave_spider
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:chicken
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:cod
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:cow
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:creeper
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:dolphin
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:donkey
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:drowned
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:elder_guardian
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:enderman
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:endermite
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:evoker
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:fox
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:frog
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:ghast
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:giant
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:glow_squid
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:goat
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:guardian
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:hoglin
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:horse
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:husk
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:illusioner
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:iron_golem
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:llama
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:magma_cube
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:mooshroom
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:mule
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:ocelot
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:panda
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:parrot
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:phantom
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:pig
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:piglin
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:piglin_brute
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:pillager
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:polar_bear
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:pufferfish
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:rabbit
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:ravager
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:salmon
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:sheep
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:shulker
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:silverfish
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:skeleton
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:skeleton_horse
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:slime
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:sniffer
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:snow_golem
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:spider
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:squid
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:stray
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:strider
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:tadpole
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:trader_llama
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:tropical_fish
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:turtle
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:vex
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:villager
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:vindicator
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:wandering_trader
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:warden
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:witch
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:wither
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:wither_skeleton
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:wolf
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:zoglin
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:zombie
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:zombie_horse
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:zombie_villager
[21:47:10] [Render thread/INFO] [ModernFix/]: Loaded entity minecraft:zombified_piglin
[21:47:10] [Render thread/ERROR] [ModernFix/]: Failed to create entity model for minecraft:player:
java.lang.RuntimeException: Provider not registered
	at org.embeddedt.modernfix.entity.EntityRendererMap$RenderConstructor.load(EntityRendererMap.java:39) ~[modernfix-forge-5.17.0+mc1.20.1.jar%23530!/:5.17.0+mc1.20.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.embeddedt.modernfix.entity.EntityRendererMap$RenderConstructor.load(EntityRendererMap.java:31) ~[modernfix-forge-5.17.0+mc1.20.1.jar%23530!/:5.17.0+mc1.20.1] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.1-jre.jar%23102!/:?] {}
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.1-jre.jar%23102!/:?] {}
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.1-jre.jar%23102!/:?] {}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.1-jre.jar%23102!/:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.1-jre.jar%23102!/:?] {}
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[guava-31.1-jre.jar%23102!/:?] {}
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[guava-31.1-jre.jar%23102!/:?] {}
	at org.embeddedt.modernfix.entity.EntityRendererMap.get(EntityRendererMap.java:74) ~[modernfix-forge-5.17.0+mc1.20.1.jar%23530!/:5.17.0+mc1.20.1] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.embeddedt.modernfix.entity.EntityRendererMap.get(EntityRendererMap.java:20) ~[modernfix-forge-5.17.0+mc1.20.1.jar%23530!/:5.17.0+mc1.20.1] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.client.event.EntityRenderersEvent$AddLayers.getRenderer(EntityRenderersEvent.java:194) ~[forge-1.20.1-47.2.0-universal.jar%23619!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:eventbus:A}
	at com.github.alexthe666.alexsmobs.client.ClientLayerRegistry.addLayerIfApplicable(ClientLayerRegistry.java:42) ~[alexsmobs-1.22.8.jar%23389!/:1.22.8] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at com.github.alexthe666.alexsmobs.client.ClientLayerRegistry.lambda$onAddLayers$1(ClientLayerRegistry.java:31) ~[alexsmobs-1.22.8.jar%23389!/:1.22.8] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23102!/:?] {re:mixin}
	at com.github.alexthe666.alexsmobs.client.ClientLayerRegistry.onAddLayers(ClientLayerRegistry.java:30) ~[alexsmobs-1.22.8.jar%23389!/:1.22.8] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.2.0.jar%23616!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.0.jar%23615!/:?] {re:mixin}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.0.jar%23615!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.0.jar%23615!/:?] {re:mixin}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_6213_(EntityRenderDispatcher.java:362) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:forge-badoptimizations.mixins.json:renderer.entity.MixinEntityRendererDispatcher from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:perf.dynamic_entity_renderers.EntityRenderDispatcherMixin from mod modernfix,pl:mixin:APP:mixins.oculus.json:MixinEntityRenderDispatcher from mod oculus,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinEntityRenderDispatcher from mod oculus,pl:mixin:APP:mixins.oculus.compat.sodium.json:copyEntity.shadows.EntityRenderDispatcherMixin from mod oculus,pl:mixin:APP:mixins.cobblemon-common.json:EntityRenderDispatcherMixin from mod cobblemon,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.EntityRenderDispatcherMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.EntityRenderDispatcherMixin from mod pehkui,pl:mixin:APP:kirin.mixin.json:MixinEntityRenderDispatcher from mod kirin,pl:mixin:APP:freecam.mixins.json:EntityRenderDispatcherAccessor from mod freecam,pl:mixin:APP:freecam.mixins.json:EntityRenderDispatcherMixin from mod freecam,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.entity.MixinEntityRenderDispatcher from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:APP:dynamic_fps-common.mixins.json:bugfix.BlockableEventLoopMixin from mod dynamic_fps,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:APP:dynamic_fps-common.mixins.json:bugfix.BlockableEventLoopMixin from mod dynamic_fps,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:APP:dynamic_fps-common.mixins.json:bugfix.BlockableEventLoopMixin from mod dynamic_fps,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23614!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain from mod notenoughcrashes,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```

**Comment by embeddedt** [comment]
Disabling `mixin.perf.dynamic_entity_renderers` should work around this for now; the option is disabled by default due to compatibility issues with mods.

**Comment by mpustovoi** [comment]
I just suddenly ran into the same problem in the logs on Forge 1.20.1 when trying to enter my world.
The game was frozen, but Modrinth said that the instance crashed
Here are the logs: https://mclo.gs/ywl0arz.
Crash report: https://mclo.gs/kye4EHM.
Maybe the crash related to something else, I just still don't get it.

**Comment by embeddedt** [comment]
This error shouldn't print anymore as of 5.22.0.
