### ISSUE TITLE
Server crash when launching

### ISSUE THREAD

**Issue by transbiod** [embeddedt/ModernFix#42]
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Hex
	at org.embeddedt.modernfix.structure.CachingStructureManager.readStructureTag(CachingStructureManager.java:46) ~[modernfix-mc1.19.2-3.0.2.jar%23785!/:3.0.2] {re:mixin,re:classloading}
	at org.embeddedt.modernfix.structure.CachingStructureManager.readStructure(CachingStructureManager.java:29) ~[modernfix-mc1.19.2-3.0.2.jar%23785!/:3.0.2] {re:mixin,re:classloading}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:533) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix.mixins.json:perf.cache_upgraded_structures.StructureManagerMixin,pl:mixin:APP:repurposed_structures.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:102) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix.mixins.json:perf.cache_upgraded_structures.StructureManagerMixin,pl:mixin:APP:repurposed_structures.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?] {re:mixin}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:92) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix.mixins.json:perf.cache_upgraded_structures.StructureManagerMixin,pl:mixin:APP:repurposed_structures.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.mergeIntoExistingPool(PoolAdditionMerger.java:103) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2] {re:classloading}
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.lambda$parsePoolsAndBeginMerger$1(PoolAdditionMerger.java:72) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.parsePoolsAndBeginMerger(PoolAdditionMerger.java:72) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2] {re:classloading}
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.mergeAdditionPools(PoolAdditionMerger.java:52) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:92) ~[forge-1.19.2-43.2.6-universal.jar%23974!/:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:163) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Hex
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 20 more

**Comment by transbiod** [comment]
[15Mar2023 15:20:32.725] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: org/apache/commons/codec/binary/Hex
	Index: 8
	Listeners:
		0: HIGH
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@76a2cd41
		2: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		3: NORMAL
		4: ASM: evilcraftcompat onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		5: ASM: integratedterminalscompat onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		6: ASM: integratedterminals onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		7: ASM: evilcraft onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@6caf3ff8
		9: ASM: me.lucko.spark.forge.ForgeSparkMod@781df278 serverInit(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		10: ASM: com.samebutdifferent.morevillagers.forge.MoreVillagersForge@62d96bd2 onServerAboutToStartEvent(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		11: ASM: integratedcrafting onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@3be1545b
		13: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@16637153
		14: ASM: class noobanidus.mods.lootr.event.HandleChunk onServerStarted(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@764b7e1b
		16: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@638ecfd5
		17: ASM: class com.minecolonies.coremod.event.FMLEventHandler onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		18: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@527c0c73
		19: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@5f981686
		20: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@728e10c8
		21: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@676b892b
		22: ASM: integrateddynamics onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		23: ASM: integrateddynamicscompat onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		24: ASM: cyclopscore onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@55460e21
		26: ASM: commoncapabilities onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		27: ASM: integratedtunnels onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		28: ASM: integratedtunnelscompat onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		29: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@4a750e29
		30: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler serverAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		31: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@487f5fff
		32: ASM: class me.desht.pneumaticcraft.common.variables.GlobalVariableManager$Listener onServerStarting(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		33: ASM: com.mrcrayfish.configured.impl.simple.SimpleConfigManager@306b1dfa onServerStarting(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		34: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@7366a50a
		35: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@16349a41
		36: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@74d2dae8
		37: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@46e0e32a
		38: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@e85009
		39: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@32bc24c7
		40: net.minecraftforge.eventbus.EventBus$$Lambda$4655/0x000000080192c000@50dbade2
		41: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@5cf7e963 serverAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		42: LOWEST
		43: ASM: class terrablender.handler.InitializationHandler onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Hex
	at TRANSFORMER/modernfix@3.0.2/org.embeddedt.modernfix.structure.CachingStructureManager.readStructureTag(CachingStructureManager.java:46)
	at TRANSFORMER/modernfix@3.0.2/org.embeddedt.modernfix.structure.CachingStructureManager.readStructure(CachingStructureManager.java:29)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:533)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:102)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:92)
	at TRANSFORMER/repurposed_structures@6.3.11+1.19.2/com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.mergeIntoExistingPool(PoolAdditionMerger.java:103)
	at TRANSFORMER/repurposed_structures@6.3.11+1.19.2/com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.lambda$parsePoolsAndBeginMerger$1(PoolAdditionMerger.java:72)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/repurposed_structures@6.3.11+1.19.2/com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.parsePoolsAndBeginMerger(PoolAdditionMerger.java:72)
	at TRANSFORMER/repurposed_structures@6.3.11+1.19.2/com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.mergeAdditionPools(PoolAdditionMerger.java:52)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.6/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:92)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:163)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Hex
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more

[15Mar2023 15:20:32.727] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Hex
	at org.embeddedt.modernfix.structure.CachingStructureManager.readStructureTag(CachingStructureManager.java:46) ~[modernfix-mc1.19.2-3.0.2.jar%23785!/:3.0.2]
	at org.embeddedt.modernfix.structure.CachingStructureManager.readStructure(CachingStructureManager.java:29) ~[modernfix-mc1.19.2-3.0.2.jar%23785!/:3.0.2]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:533) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:102) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:92) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?]
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.mergeIntoExistingPool(PoolAdditionMerger.java:103) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2]
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.lambda$parsePoolsAndBeginMerger$1(PoolAdditionMerger.java:72) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.parsePoolsAndBeginMerger(PoolAdditionMerger.java:72) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2]
	at com.telepathicgrunt.repurposedstructures.misc.pooladditions.PoolAdditionMerger.mergeAdditionPools(PoolAdditionMerger.java:52) ~[repurposed_structures_forge-6.3.11+1.19.2.jar%23854!/:6.3.11+1.19.2]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:92) ~[forge-1.19.2-43.2.6-universal.jar%23974!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:163) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23969!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Hex
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 20 more
[15Mar2023 15:20:32.748] [Server thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@4ad8d36f
[15Mar2023 15:20:32.749] [Server thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@2f4d3709
[15Mar2023 15:20:32.779] [Server thread/DEBUG] [mixin/]: Mixing feature.branding.BrandingControlMixin from modernfix.mixins.json into net.minecraftforge.internal.BrandingControl

**Comment by transbiod** [comment]
Minecraft 1.19.2
Forge 43.2.6
Modernfix 3.1.1

**Comment by transbiod** [comment]
Ok, i was stupid enough to completely miss that i loaded an older version of moderndix on my server. Will test with the 3.1.1 and report back

**Comment by transbiod** [comment]
Yeah, it was fixed, sorry for unneeded spam
