### ISSUE TITLE
Modernfix not compatible with Undergarden  (dedicated server, 1.20.1, forge version 47.3.7)

### ISSUE THREAD

**Issue by muppetenergy** [embeddedt/ModernFix#458]
### Bug Description

I added Undergarden to my server, but we are unable to use it because the server crashes every time we try to enter a portal. 
Here is what shows on the player's side. No crash reports are generated on client side, only server. 
![image](https://github.com/user-attachments/assets/d90e08e2-ec2c-4ff7-a278-d1f303b50070)
![image](https://github.com/user-attachments/assets/e723dae6-847d-4b26-a638-cfa760dccbe3)

Here's the screenshot I could snag quickly as text was flying, but i'll post the logs too 
![image](https://github.com/user-attachments/assets/33cc1164-e096-4e70-89db-cd160d6305b8)

### Reproduction Steps

(all mods are up to date) 
-added Undergarden to dedicated server (and Undergarden Delight) 
-created a portal with stone bricks and catalyst, in creative mode 
-walk/jump into portal 
-server crashes 

### Log File

[latest(2).log](https://github.com/user-attachments/files/16739531/latest.2.log)
[crash-2024-08-25_03.20.40-server.txt](https://github.com/user-attachments/files/16739532/crash-2024-08-25_03.20.40-server.txt)

**Comment by embeddedt** [comment]
From line 213 of your crash report:

```
"Worker-Main-2" daemon prio=4 Id=55 RUNNABLE
	at TRANSFORMER/forge@47.3.7/net.minecraftforge.common.extensions.IForgeBlockState.getLightEmission(IForgeBlockState.java:79)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$Properties.m_284110_(BlockBehaviour.java:1002)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$Properties$$Lambda$1434/0x00007f768063dd00.m_61030_(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60643_(BlockBehaviour.java:543)
	at TRANSFORMER/forge@47.3.7/net.minecraftforge.common.extensions.IForgeBlock.isValidSpawn(IForgeBlock.java:247)
	at TRANSFORMER/forge@47.3.7/net.minecraftforge.common.extensions.IForgeBlockState.isValidSpawn(IForgeBlockState.java:158)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.canSpawnAtBody(NaturalSpawner.java:321)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.SpawnPlacements$Type.canSpawnAt(SpawnPlacements.java:179)
	...
```

This indicates the server is likely in the middle of generating chunks (triggered by UG trying to place a portal), and was not able to finish within 60 seconds, causing the watchdog to crash it. Setting `max-tick-time=-1` in `server.properties` is recommended if you have mods installed that slow down worldgen a lot. The crash report is just blaming ModernFix because it optimizes one of the functions in use; I don't think this is a ModernFix bug.

You may also want to add the Fullstack Watchdog mod so that the `Worker-Main` stacktraces will show you the full context instead of just the first few lines, that may help narrow down *which* mod is slowing down worldgen. My guess is it will be Undergarden if you are entering the dimension, but it could be a conflict with something else.

**Comment by muppetenergy** [comment]
oh shoot i didn't see the notification that you'd responded. thank you for the info! i'll check out that mod too
