### ISSUE TITLE
[1.21.x][Neoforge] Mod causing game to not tick and requires me to force close the game

### ISSUE THREAD

**Issue by ffuentesm** [embeddedt/ModernFix#461]
### Bug Description

After trying to /reload my world things are weird. I cant use item, I can only run and jump, and the running does not stop, and new chunks will not load. 
Looking at the log this message is where it starts
[ModernFix integrated server watchdog/ERROR] [org.embeddedt.modernfix.world.IntegratedWatchdog/]: A single server tick has taken 40001, more than 40000 milliseconds

if I uninstall the mod the game works. 

### Reproduction Steps

I am not sure what caused it. 

But the log keeps having this message going over and over.
"ForkJoinPool.commonPool-worker-6" daemon prio=5 Id=26 WAITING on java.util.concurrent.ForkJoinPool@63a092fc
	at java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@63a092fc
	at java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
	at java.base@21.0.3/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
	at java.base@21.0.3/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
	at java.base@21.0.3/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

### Log File

[2024-09-12-7.log](https://github.com/user-attachments/files/16988328/2024-09-12-7.log)

**Comment by embeddedt** [comment]
If the integrated server watchdog message is shown, it means another mod has caused the game to freeze. Usually this happens when mods have buggy code running during world generation. Looking at the log, the `visibletraders` mod appears to be the issue; it is trying to load chunks in the middle of a structure trying to spawn with villagers. Please try removing it.
