### ISSUE TITLE
Crash on making a new world

### ISSUE THREAD

**Issue by TishinaVC** [embeddedt/ModernFix#466]
### Bug Description
1.20.1 forge 47.3.10
on loading world it crashes to desktop

### Reproduction Steps

attempt to make a new world

### Log File

[latest.log](https://github.com/user-attachments/files/17232999/latest.log)
[crash.txt](https://github.com/user-attachments/files/17233000/crash.txt)

**Comment by embeddedt** [comment]
I am pretty sure this is caused by another mod, it seems to crash deserializing a loot modifier. ModernFix does not add any loot modifiers.

```
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:chests/pillager_outpost 
	at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236) ~[client-1.20.1-20230612.114412-srg.jar%231516!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:doapi-common.mixins.json:DataFixerMixin,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38) ~[client-1.20.1-20230612.114412-srg.jar%231516!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:doapi-common.mixins.json:DataFixerMixin,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.20.1-20230612.114412-srg.jar%231516!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:doapi-common.mixins.json:DataFixerMixin,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.20.1-20230612.114412-srg.jar%231516!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:doapi-common.mixins.json:DataFixerMixin,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:A}
	at net.minecraftforge.common.loot.LootTableIdCondition$Serializer.deserialize(LootTableIdCondition.java:76) ~[forge-1.20.1-47.3.10-universal.jar%231521!/:?] {re:classloading}
	at net.minecraftforge.common.loot.LootTableIdCondition$Serializer.m_7561_(LootTableIdCondition.java:65) ~[forge-1.20.1-47.3.10-universal.jar%231521!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.20.1-20230612.114412-srg.jar%231516!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%23107!/:?] {}
	at net.minecraftforge.common.loot.IGlobalLootModifier.lambda$static$1(IGlobalLootModifier.java:39) ~[forge-1.20.1-47.3.10-universal.jar%231521!/:?] {re:classloading}
```
