### ISSUE TITLE
Console NPE

### ISSUE THREAD

**Issue by Sa1ZeR** [embeddedt/ModernFix#473]
### Bug Description

The message appears periodically, the server continues to work.

### Reproduction Steps

random spam 

### Log File

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:678) ~[fastutil-8.5.6.jar%2389!/:?] {}
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:1083) ~[fastutil-8.5.6.jar%2389!/:?] {}
        at net.minecraft.nbt.CompoundTag.m_6434_(CompoundTag.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.nbt_memory_usage.CompoundTagMixin,pl:mixin:APP:canary.mixins.json:alloc.nbt.CompoundTagMixin,pl:mixin:A}
        at net.minecraft.nbt.NbtIo.m_128950_(NbtIo.java:265) ~[server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:mixin,re:classloading}
        at net.minecraft.nbt.NbtIo.m_128941_(NbtIo.java:234) ~[server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63708_(RegionFileStorage.java:79) ~[server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at net.minecraft.world.level.chunk.storage.IOWorker.m_63535_(IOWorker.java:260) ~[server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at net.minecraft.world.level.chunk.storage.IOWorker.m_63553_(IOWorker.java:250) ~[server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:60) [server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [server-1.19.2-20220805.130853-srg.jar%23315!/:?] {re:classloading}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] {}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by embeddedt** [comment]
I think this is a variant of #446 or #448, so to keep the issue tracker from becoming overloaded I'll close this report in favor of those.
