### ISSUE TITLE
The maximum number of Windows file names is too short

### ISSUE THREAD

**Issue by 1luik** [embeddedt/ModernFix#485]
### Bug Description

![affa5a8c58d5934eea66b9512b62b5a4](https://github.com/user-attachments/assets/19d4827d-7dba-42b5-b709-23844064438e)

java.io.IOException: File [G:\恢复\测试服务器-新\modernfix\structureCacheV1\apotheosis_tower_leaf_38f64271eabbdd0534b9caadb9282adb40fa6f672927450e045c5bd2a0a1b803.nbt]
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.nbt.NbtIo.m_128937_(NbtIo.java:541)
        at TRANSFORMER/modernfix@5.17.0+mc1.20.1/org.embeddedt.modernfix.structure.CachingStructureManager.getCachedUpgraded(CachingStructureManager.java:104)
        at TRANSFORMER/modernfix@5.17.0+mc1.20.1/org.embeddedt.modernfix.structure.CachingStructureManager.readStructureTag(CachingStructureManager.java:74)
        at TRANSFORMER/modernfix@5.17.0+mc1.20.1/org.embeddedt.modernfix.structure.CachingStructureManager.readStructure(CachingStructureManager.java:37)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:538)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:108)
        at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.cache.LocalCache.lambda$computeIfAbsent$0(LocalCache.java:4219)
        at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.cache.LocalCache$LoadingValueReference.compute(LocalCache.java:3571)
        at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.cache.LocalCache$Segment.compute(LocalCache.java:2247)
        at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.cache.LocalCache.compute(LocalCache.java:4212)
        at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.cache.LocalCache.computeIfAbsent(LocalCache.java:4219)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:98)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230359_(StructureTemplateManager.java:86)
        at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_227299_(SinglePoolElement.java:81)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_214015_(SinglePoolElement.java:115)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement.m_227238_(JigsawPlacement.java:305)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.structures.JigsawStructure.m_214086_(JigsawStructure.java:82)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.Structure.m_262864_(Structure.java:156)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.Structure.m_226596_(Structure.java:86)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkGenerator.m_223104_(ChunkGenerator.java:513)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkGenerator.m_254811_(ChunkGenerator.java:466)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkGenerator.m_255037_(ChunkGenerator.java:448)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus.m_289181_(ChunkStatus.java:54)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643)
        at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
        at TRANSFORMER/k_multi_threading@1.0.0/n1luik.K_multi_threading.core.Base$ForkJoinWorkerThread_.run(Base.java:156)
Caused by: java.io.FileNotFoundException: G:\恢复\测试服务器-新\modernfix\structureCacheV1\apotheosis_tower_leaf_38f64271eabbdd0534b9caadb9282adb40fa6f672927450e045c5bd2a0a1b803.nbt (系统找不到指定的文件。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.nbt.NbtIo.m_128937_(NbtIo.java:538)
        ... 41 more

### Reproduction Steps

unknown

### Log File

。

**Comment by embeddedt** [comment]
Fixed in 5.19.7.
