### ISSUE TITLE
Game crashes when modifying options in the ModMenu config screen on 1.21.4

### ISSUE THREAD

**Issue by DemonGamDev** [embeddedt/ModernFix#501]
### Bug Description

The error only occurs when the config button is clicked, so just having Mod Menu installed will not cause the crash. Manually modifying the config file still correctly applies changes, though attempting to open Mod Menu's config screen will reset options. Once the button is clicked, the game will briefly freeze with the words "saving world" appearing before crashing. The latest crash log contains the following error message:

`java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4185.method_25355(net.minecraft.class_2561)" because "this.doneButton" is null
	at knot//org.embeddedt.modernfix.screen.ModernFixConfigScreen.method_25394(ModernFixConfigScreen.java:48)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$51(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$zmd000$fabric-screen-api-v1$onRenderScreen(class_757.java:912)
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

### Reproduction Steps

- Install the latest version of Mod Menu and ModernFix
- Open the Mods tab in-game
- Select ModernFix
- Click on the 'configure' in the top right of the ModernFix tab

### Log File

[latest.log](https://github.com/user-attachments/files/18277750/latest.log)

**Comment by DemonGamDev** [comment]
Issue still occurs when using the beta 1.21.4 versions as well.

**Comment by embeddedt** [comment]
I cannot reproduce this with Mod Menu 13.0.0-beta.1 and ModernFix 5.20.1. Where did you download ModernFix from?

**Comment by DemonGamDev** [comment]
I used a version from GitHub actions, a little before it was uploaded to Modrinth. I haven't had the issue after reinstalling it.

**Comment by embeddedt** [comment]
Ok, perhaps it was just an issue in an older beta.
