### ISSUE TITLE
`NoClassDefFoundError: net/minecraft/client/sounds/MusicManager`

### ISSUE THREAD

**Issue by SettingDust** [embeddedt/ModernFix#55]
I'm not sure whether should it treat as a bug. It causing by `Paxi`(A global pack loader) loading resource pack on server side. It should not working. But seems that modernfix think the resources are useful?
```
java.lang.NoClassDefFoundError: net/minecraft/client/sounds/MusicManager
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
        at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
        at TRANSFORMER/modernfix@2.2.1/org.embeddedt.modernfix.entity.EntityDataIDSyncHandler.onDatapackSyncEvent(EntityDataIDSyncHandler.ja
va:45)
        at net.minecraftforge.eventbus.ASMEventHandler_7_EntityDataIDSyncHandler_onDatapackSyncEvent_OnDatapackSyncEvent.invoke(.dynamic)
```

**Comment by embeddedt** [comment]
I pushed a commit with the fix; it will be included in the next release.

**Comment by embeddedt** [comment]
Should be fixed.
