### ISSUE TITLE
Getting a werid issue after updating This Mod

### ISSUE THREAD

**Issue by ModernGamingWorld** [embeddedt/ModernFix#87]
I have a custom pack for 1.16.5 and after updating this mod, the game won't load and I get this in my log file

[08May2023 11:13:30.337] [pool-3-thread-1/INFO] [ModernFix/]: Bypassed Mojang DFU
[08May2023 11:13:30.359] [pool-3-thread-1/INFO] [mixin/]: Mixing AccessorAbstractArrowEntity from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.entity.projectile.AbstractArrowEntity
[08May2023 11:13:30.402] [pool-3-thread-1/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Patching TemptGoal#isTempting
[08May2023 11:13:30.719] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed modernfix-forge.mixins.json:bugfix.remove_block_chunkloading.RemoveBlockGoalMixin -> net.minecraft.entity.ai.goal.BreakBlockGoal: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/entity/ai/goal/BreakBlockGoal::fireGriefingEvent with priority 1000 cannot inject into net/minecraft/entity/ai/goal/BreakBlockGoal::func_75250_a()Z merged by com.performant.coremod.mixin.goal.BreakBlockGoalMixin with priority 1000 [PREINJECT Applicator Phase -> modernfix-forge.mixins.json:bugfix.remove_block_chunkloading.RemoveBlockGoalMixin -> Prepare Injections ->  -> redirect$zfa000$fireGriefingEvent(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/LivingEntity;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/ai/goal/BreakBlockGoal::fireGriefingEvent with priority 1000 cannot inject into net/minecraft/entity/ai/goal/BreakBlockGoal::func_75250_a()Z merged by com.performant.coremod.mixin.goal.BreakBlockGoalMixin with priority 1000 [PREINJECT Applicator Phase -> modernfix-forge.mixins.json:bugfix.remove_block_chunkloading.RemoveBlockGoalMixin -> Prepare Injections ->  -> redirect$zfa000$fireGriefingEvent(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/LivingEntity;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_51]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962) [?:1.8.0_51]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987) [?:1.8.0_51]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) [?:1.8.0_51]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) [?:1.8.0_51]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) [?:1.8.0_51]
	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:164) [?:?]
	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24) [?:?]
	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37) [?:?]
	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$783/1999812437.get(Unknown Source) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$789/1339830544.accept(Unknown Source) [?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) [?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) [?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) [?:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) [?:?]
	at net.minecraft.client.main.Main$$Lambda$723/2056109041.run(Unknown Source) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[08May2023 11:13:30.755] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[08May2023 11:13:30.755] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[08May2023 11:13:30.755] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[08May2023 11:13:30.755] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[08May2023 11:13:30.756] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$506/1421004802.call(Unknown Source)
[08May2023 11:13:30.757] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[08May2023 11:13:30.757] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[08May2023 11:13:30.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[08May2023 11:13:30.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
[08May2023 11:13:30.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[08May2023 11:13:30.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[08May2023 11:13:30.763] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[08May2023 11:13:30.764] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[08May2023 11:13:30.764] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[08May2023 11:13:30.764] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[08May2023 11:13:30.764] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[08May2023 11:13:30.764] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[08May2023 11:13:30.764] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[08May2023 11:13:30.765] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:164)
[08May2023 11:13:30.766] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$783/1999812437.get(Unknown Source)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$789/1339830544.accept(Unknown Source)
[08May2023 11:13:30.767] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$723/2056109041.run(Unknown Source)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08May2023 11:13:30.768] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [modernfix-forge.mixins.json:bugfix.remove_block_chunkloading.RemoveBlockGoalMixin] from phase [DEFAULT] in config [modernfix-forge.mixins.json] FAILED during APPLY
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 40 more
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/ai/goal/BreakBlockGoal::fireGriefingEvent with priority 1000 cannot inject into net/minecraft/entity/ai/goal/BreakBlockGoal::func_75250_a()Z merged by com.performant.coremod.mixin.goal.BreakBlockGoalMixin with priority 1000 [PREINJECT Applicator Phase -> modernfix-forge.mixins.json:bugfix.remove_block_chunkloading.RemoveBlockGoalMixin -> Prepare Injections ->  -> redirect$zfa000$fireGriefingEvent(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/LivingEntity;)Z -> Prepare]
[08May2023 11:13:30.769] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
[08May2023 11:13:30.770] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[08May2023 11:13:30.770] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
[08May2023 11:13:30.770] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[08May2023 11:13:30.771] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 40 more

**Comment by ModernGamingWorld** [comment]
Update, Disabling this mod and was able to get my 1.16.5 pack to load. idk if u would like to me to zip up the version of the pack to see what's going on

**Comment by ModernGamingWorld** [comment]
@embeddedt It crashed again, but this time loading into a world after removing ModernFix I was able to log in with no crashing



[crash-2023-05-08_12.29.15-client.txt](https://github.com/embeddedt/ModernFix/files/11423675/crash-2023-05-08_12.29.15-client.txt)

**Comment by embeddedt** [comment]
Please try the following test build.

[testbuild.zip](https://github.com/embeddedt/ModernFix/files/11424867/testbuild.zip)

**Comment by ModernGamingWorld** [comment]
@embeddedt Tested with that Build and I was able to launch and Login into a world without any crashing

**Comment by embeddedt** [comment]
This should be fixed by 1.14.2.
